### ISSUE TITLE
Script is Stopped Working

### ISSUE THREAD

**Issue by sudhir-trigyn** [pallupz/covid-vaccine-booking#46] opened 2021-05-05 15:35 UTC
![image](https://user-images.githubusercontent.com/46558791/117168231-9989e800-ade5-11eb-81fe-ec99ca14285d.png)

**Comment by pallupz** [comment] 2021-05-05 15:37
Yup.. Updated the readme

**Comment by pallupz** [comment] 2021-05-05 15:37
Duplicate of #45

**Closed by pallupz** 2021-05-05 15:37 UTC
