### ISSUE TITLE
after selecting auto booking still asking for inputs like indexofcentre.indexofslot 

### ISSUE THREAD

**Issue by devansh7777** [pallupz/covid-vaccine-booking#56] opened 2021-05-05 21:52 UTC
bro i was searching for slots in Bangalore and an alert came on one of the telegram bots for 100 slots. But the script didn't show any. Is there something wrong with what i am doing here?
also i tried using it for my family in rajasthan i got a hit yet it didn't auto book it and asked for  indexofcentre.indexofslot the  availability was just 1(i set minimum number of vaccines required to 1 too). kindly help bro.

**Comment by demon12345678910** [comment] 2021-05-06 01:15
I can vouch for this, in Bangalore Manipal opened up today 6:30 am and yesterday at 5pm at both occurrences it did not show up. While other communicator apps caught it. @pallupz any idea why this is?

**Comment by bitshiftr** [comment] 2021-05-06 01:24
> I can vouch for this, in Bangalore Manipal opened up today 6:30 am and yesterday at 5pm at both occurrences it did not show up. While other communicator apps caught it. @pallupz any idea why this is?

I believe there are 2 things at play here:

1] script looks for slots from the next day, not the same day. 
2] Also, I noticed something interesting today - on the Cowin website, if you search by pincode, even when new slots open up it doesn't get updated. When I got the alert from Telegram, I was logged in to the site and searching via pincode and it didn't show Manipal, but when I changed to district based search, it showed the Manipal slots, but it was too late for me to make the booking.

**Comment by demon12345678910** [comment] 2021-05-06 04:10
Thank you @bitshiftr for the response. I would like to add some more details so that the problem is better explained. Let me de-couple the problems
1. Slots for the same day - I think your workaround should work. Manipal today at 6:30 AM was for today and didn't show up. Probably since the slot was for today.
2. Slots for the next day - This still remains to be a problem. On May 05 I was using the program sharp at 5 pm Manipal still didn't show up this was for the next day. I was polling at 10 seconds. So this problem still remains open.

**Comment by bitshiftr** [comment] 2021-05-06 04:29
I have mentioned this in one of the other threads - what I observed today
was that if you are doing a pin code based search, open slots don't show up
at all (I was on the cowin site doing manual search based on Telegram
alert), but when I switched over to district based search, Manipal showed
up immediately with open slots, but by the time I clicked through to the
booking, it was all gone. It appears that there is a delay in indexing on
the Cowin portal for pin code based searches.

**Comment by demon12345678910** [comment] 2021-05-06 04:45
Got it, just to add here I am running the script via the district and not the pin code method and still, the delay does exist.

**Comment by pallupz** [comment] 2021-05-06 05:48
Is there still an issue here or can I close this?

**Comment by demon12345678910** [comment] 2021-05-06 06:00
@pallupz can you check once if we have any delay or lag. Manipal ideally didn't show up. If you could check and verify once that would be really useful :)

**Comment by pallupz** [comment] 2021-05-06 06:41
Read the first paragraph here: https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2

**Closed** 2021-05-06 06:41 UTC
