### ISSUE TITLE
OTP problem

### ISSUE THREAD

**Issue by nishant0010** [pallupz/covid-vaccine-booking#42] opened 2021-05-05 14:11 UTC
I Get this error -
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/auth/generateMobileOTP (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

how to fix it.

**Comment by pallupz** [comment] 2021-05-05 14:32
Duplicate of #39

**Closed by pallupz** 2021-05-05 14:32 UTC
