### ISSUE TITLE
After 13+ minutes script terminating with SSL Error 

### ISSUE THREAD

**Issue by dhriti122** [pallupz/covid-vaccine-booking#104] opened 2021-05-06 15:50 UTC
Please check this error 

After 13+ minutes script terminating with SSL Error 
<img width="933" alt="SSLError" src="https://user-images.githubusercontent.com/6406814/117328016-35a50500-ae61-11eb-8436-8a5bde461acb.PNG">

**Comment by pallupz** [comment] 2021-05-06 19:28
duplicate of #17

**Closed by pallupz** 2021-05-06 19:28 UTC
