### ISSUE TITLE
Get OTP Call failing with 403

### ISSUE THREAD

**Issue by DSPLive** [pallupz/covid-vaccine-booking#65] opened 2021-05-06 05:25 UTC
Getting below error when trying to get OTP since yesterday evening.

```
Unable to Create OTP
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
Press any key to continue . . .|
```

**Comment by mah2001** [comment] 2021-05-06 05:31
I am also getting same error since last night
please help me too

**Comment by pallupz** [comment] 2021-05-06 05:46
Duplicate of https://github.com/pallupz/covid-vaccine-booking/issues/45

Please use latest version

**Comment by DSPLive** [comment] 2021-05-06 05:46
Issue not observed with the latest version. Closing the issue. Million thanks for this bot :) Once I get vaccinated I will send you beers. Cheers !!

**Closed** 2021-05-06 05:46 UTC
Labels: not-an-issue
