### ISSUE TITLE
OTP error

### ISSUE THREAD

**Issue by sharpant-dot** [pallupz/covid-vaccine-booking#83] opened 2021-05-06 11:14 UTC
Unable to Create OTP
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

Press any key to continue . . .

**Comment by pallupz** [comment] 2021-05-06 11:16
Duplicate of #82

**Closed by pallupz** 2021-05-06 11:16 UTC
