### ISSUE TITLE
Error while running code

### ISSUE THREAD

**Issue by Ashikarames98** [pallupz/covid-vaccine-booking#40] opened 2021-05-05 13:57 UTC
I'm facing an error while running your code :

Here is a snippet of it: (Occurs right after I enter mobile number and it requests for otp)
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/auth/generateMobileOTP (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
Exiting Script'

Please help!! :(

**Comment by pallupz** [comment] 2021-05-05 13:58
Seems like a duplicate of: #17

**Closed by pallupz** 2021-05-05 13:58 UTC
