### ISSUE TITLE
My attempt at automating the entire operation ;)

### ISSUE THREAD

**Issue by bombardier-gif** [pallupz/covid-vaccine-booking#44] opened 2021-05-05 15:15 UTC
My main painpoint was that

1. I had to enter the OTP whenever the token expired
2. I had to manually choose the slot
3. The frequency of polling was not enough to book slots 

**Hence I automated the entire thing end-to-end ;) ** 

Please share your thoughts on it. 

Code and steps to install are here. https://github.com/bombardier-gif/covid-vaccine-booking
Its hacky and dirty. Pull requests are welcome ;)

**Comment by pallupz** [comment] 2021-05-05 15:58
Hey - That looks cool. A little too much setting up for lay person but I dont see much of a workaround either.

Unfortunately, it doesn't matter. Requests are now getting blocked

**Comment by bombardier-gif** [comment] 2021-05-05 16:08
Oh no. Please let me know if you find any workaround on it.

**Comment by pallupz** [comment] 2021-05-05 16:09
Sure thing

**Comment by botmon99** [comment] 2021-05-05 17:05
It seems to be working now right?
It would be amazing if you updated your version @bombardier-gif

**Comment by bombardier-gif** [comment] 2021-05-05 17:06
I already did @botmon99 Let me know if you need any help setting it up

**Comment by botmon99** [comment] 2021-05-05 17:13
hey that's super cool!
I was just wondering if it was possible to set a specific slot time as the first preference with auto-booking on
e.g. 1.3 as the first preference

**Comment by pallupz** [comment] 2021-05-05 17:17
@botmon99 all you need to do is edit this line: https://github.com/pallupz/covid-vaccine-booking/blob/816f2231d9286209afbcf665b0c3a01803e943cf/src/utils.py#L232

**Comment by pallupz** [comment] 2021-05-05 17:17
Although, if a third slot is not available, you might have to do exception handling for that.

**Comment by bombardier-gif** [comment] 2021-05-05 17:22
I used a randomizer to select a slot. This helped in a much better success rate

**Comment by devansh7777** [comment] 2021-05-06 00:19
@bombardier-gif I tried your way of automating the sms gig it just didn't work out for me. The first applet i made showed error with the message rate limited by remote server : 'extendclass link' . Then i made two other applets with new extendclass links and they just dont catch the recieved message. i followed  you method step to step exactly. Help me out man.

**Comment by bombardier-gif** [comment] 2021-05-06 02:53
One way to get around it is. Create an account with extendclass site (its free) and then create a new link. Let me know if it helps

**Comment by bombardier-gif** [comment] 2021-05-06 05:14
Also @devansh7777 Could you share your extendsclass link? It could happen that your ISP could be rate limited by them if they used the same IP address.

**Comment by urajeya** [comment] 2021-05-06 05:47
@bombardier-gif Hi I have the same issue as devansh7777, tried a new url after login also...... No luck

**Comment by bombardier-gif** [comment] 2021-05-06 05:58
@urajeya Can you please share your extendclass link?

**Comment by urajeya** [comment] 2021-05-06 06:08
@bombardier-gif https://json.extendsclass.com/bin/5d7a6e6f80d9

**Comment by lets-get-vaccinated** [comment] 2021-05-06 07:13
> I used a randomizer to select a slot. This helped in a much better success rate

What is an improved success rate compared to the base version?

**Comment by bombardier-gif** [comment] 2021-05-06 07:17
Anecdotal: It usually instantly books a slot. And also on the next try it user another available random combination.

**Comment by urajeya** [comment] 2021-05-06 07:24
@bombardier-gif  Is the .exe file on your page with the random version?

**Comment by pallupz** [comment] 2021-05-06 07:31
I'm closing this ticket to cleanup my issues list. Feel free to continue your discussion here though.

**Closed by pallupz** 2021-05-06 07:31 UTC

**Comment by bombardier-gif** [comment] 2021-05-06 07:36
@urajeya It is working for me. Did you try the premium version of IFTTT?

**Comment by urajeya** [comment] 2021-05-06 07:43
@bombardier-gif  Yeah, have taken the 7day Pro trial of IFTTT.  I am not sure what's the issue here. Thanks for your help.

**Comment by devansh7777** [comment] 2021-05-06 09:48
@bombardier-gif  https://json.extendsclass.com/bin/d2b36ae31841 this is the link i created, i also borrowed a premium account of ifttt from a friend. i will try to make an account on extendclass as you suggested.

**Comment by bombardier-gif** [comment] 2021-05-06 09:59
@urajeya and @devansh7777 Let me update my solution without using the extendsclass solution. It still works for me so its a bit hard to debug.
Give me couple of hours!

**Comment by axd123** [comment] 2021-05-06 10:06
I've been trying to cut out a lot of the options and make a personalized script. 
programming wise, I'm probably 0 on a scale from 1-10. 
I can understand the code and conditions. 
Sadly, I cant seem to compile the code my windows laptop. extreme noob problems. I know. 
My pc is not being able to pull requests, but i sorted that out. 
now, though I think my pc is facing issue pulling modules from the utils file. 
any help or comments will be appreciated. 
Also, kudos to you guys, the code works well enough. 
i feel the lags that a user introduces is a painpoint - and i wanted to cut most of it out, except for the otp which would extremely difficult to automate I'm guessing. 
![image](https://user-images.githubusercontent.com/9998583/117280982-cb9c5800-ae80-11eb-91a7-0a0552314e3c.png)

**Comment by iashishsethia** [comment] 2021-05-06 10:23
Mine isn't probably working automatically because it asks me to manually enter OTP every 13-14 minutes.
My extends Class URL is working fine
https://json.extendsclass.com/bin/980ccb487106
So is IFTTT.
I have updated my mobile number and the extends class as described in the steps.
PS: I'm a coding noob.

**Comment by bombardier-gif** [comment] 2021-05-06 10:28
Give me couple of hours I shall try to address all the issues mentioned by asish sethia and axd. Overall i am trying to take away the extendsclassURL

**Comment by devansh7777** [comment] 2021-05-06 10:47
@bombardier-gif my new applet is running fine now, like it shows applet ran everytime there's an otp in my inbox.
what I think the problem is with my code now. I did  {Search for your__mobile__number and replace with your mobile number} this step in vs code saved it, replaced the extendclass link too. But when i run the exe file it still asks for the mobile number. so i guess i am doing something wrong here. this might be the final obstacle for me :D

**Comment by pallupz** [comment] 2021-05-06 10:50
@axd123 install the dependencies.

**Comment by axd123** [comment] 2021-05-06 11:09
> @axd123 install the dependencies.

already done. on pip-ing them again, get prompted 

> Requirement already satisfied: inputimeout in c:\users\akhpp\appdata\local\programs\python\python38\lib\site-packages (1.0.4)

**Comment by pallupz** [comment] 2021-05-06 11:21
Well its throwing ModuleNotFoundError. So clearly its not able to find the package.

**Comment by axd123** [comment] 2021-05-06 11:22
@pallupz 
yeah I know what you mean. I'm guessing youre not using windows to code, are you?

**Comment by pallupz** [comment] 2021-05-06 11:26
I am. In fact I pretty much only use Windows

**Comment by bombardier-gif** [comment] 2021-05-06 12:09
@devansh7777 you are supposed to use the script using the python command, and not the exe
@pallupz Can you tell me how to update the exe (i have not used windows in a while)

**Comment by pallupz** [comment] 2021-05-06 13:30
You just have to install ```pyinstaller``` and from the code folder run ```pyinstaller --onefile <your-code.py>```

**Comment by pallupz** [comment] 2021-05-06 13:31
Even better would be offloading that activity to GitHub Actions, like I have using this yaml: https://github.com/pallupz/covid-vaccine-booking/blob/main/.github/workflows/main.yml

**Comment by devansh7777** [comment] 2021-05-06 14:34
@bombardier-gif check @pallupz last update he added the feature to search for vaccines from today. see if you can automate that script too.  Also your method worked for me! but it scans from a day after so that might slow down the process.

**Comment by axd123** [comment] 2021-05-06 15:15
@pallupz 


> I am. In fact I pretty much only use Windows

What version of python are you using, if you don't mind my asking?
I think I should fresh install python and then try tinkering with it. 

I actually used an older version of your script today (since I didn't want so many options to increase my human lag) and successfully booked my friends' vaccinations. Some coffee is coming your way.

**Comment by pallupz** [comment] 2021-05-06 15:18
@axd123 Python 3.9 but really anything 3.6+ is fine

**Comment by iashishsethia** [comment] 2021-05-06 15:31
![image](https://user-images.githubusercontent.com/83760955/117325226-239d8380-aeae-11eb-9f31-ef50ac2a46ec.png)
I ran the file but I haven't received any OTP.
And it is stuck at 
```
OTP SMS len is:0
OTP SMS is:
```

**Comment by bombardier-gif** [comment] 2021-05-06 15:37
Hi All,

I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code. 
Let me know how it works out.

**Comment by devansh7777** [comment] 2021-05-06 15:38
> Hi All,
> 
> I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> Let me know how it works out.

does it scan for slots from the present day ?

**Comment by devansh7777** [comment] 2021-05-06 15:50
> > Hi All,
> > I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> > Let me know how it works out.
> 
> does it scan for slots from the present day ?

@bombardier-gif  kindly add the feature so that it can scan from the present day like @pallupz did. It is impossible here in bagalore to get a slot.

**Comment by devansh7777** [comment] 2021-05-06 15:52
also all the codes works smooth, great minds you guys!

**Comment by bombardier-gif** [comment] 2021-05-06 16:14
@pallupz As people have reported that this code works, would you mind linking this up in your readme, so that more people could discover and benefit?

**Comment by bombardier-gif** [comment] 2021-05-06 16:22
@devansh7777 Did you use my code to book a slot?

**Comment by urajeya** [comment] 2021-05-06 16:25
@bombardier-gif  Great work with the IFFFT logic , now it works flawlessly. The .EXE makes it much easier to run on PC
@pallupz Your Playground was GREAT!! You helping  + taking inputs from others to continuously improve it is also very commendable 👍
Will buy both a coffee/beer once I successfully register 🍻, had been trying today but no luck😅

The slots fill up very fast, can the time interval between checks be reduced below 5 seconds? Also as I was using pallupz's  .EXE file, I think picking a random slot instead of 1.1 would be more successful. Will try the .EXE from bombardier tomorrow.

Also for both the .EXE once the slots are filled they don't reset to zero. Picture attached.
![CoWin Run Error](https://user-images.githubusercontent.com/83747177/117332626-b0980b00-aeb5-11eb-9753-fea24840e7fe.jpg)

**Comment by bombardier-gif** [comment] 2021-05-06 17:45
> > Hi All,
> > I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> > Let me know how it works out.
> 
> does it scan for slots from the present day ?

Yes I just refreshed from the main repo

**Comment by bombardier-gif** [comment] 2021-05-06 17:45
> @bombardier-gif Great work with the IFFFT logic , now it works flawlessly. The .EXE makes it much easier to run on PC
> @pallupz Your Playground was GREAT!! You helping + taking inputs from others to continuously improve it is also very commendable 👍
> Will buy both a coffee/beer once I successfully register 🍻, had been trying today but no luck😅
> 
> The slots fill up very fast, can the time interval between checks be reduced below 5 seconds? Also as I was using pallupz's .EXE file, I think picking a random slot instead of 1.1 would be more successful. Will try the .EXE from bombardier tomorrow.
> 
> Also for both the .EXE once the slots are filled they don't reset to zero. Picture attached.
> ![CoWin Run Error](https://user-images.githubusercontent.com/83747177/117332626-b0980b00-aeb5-11eb-9753-fea24840e7fe.jpg)

@urajeya I allow even 1 sec refresh rate.

**Comment by bombardier-gif** [comment] 2021-05-06 18:20
> > > Hi All,
> > > I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> > > Let me know how it works out.
> > 
> > 
> > does it scan for slots from the present day ?
> 
> @bombardier-gif kindly add the feature so that it can scan from the present day like @pallupz did. It is impossible here in bagalore to get a slot.

@urajeya I updated the code. Please let me know if worked for you

**Comment by devansh7777** [comment] 2021-05-06 21:29
> > > > Hi All,
> > > > I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> > > > Let me know how it works out.
> > > 
> > > 
> > > does it scan for slots from the present day ?
> > 
> > 
> > @bombardier-gif kindly add the feature so that it can scan from the present day like @pallupz did. It is impossible here in bagalore to get a slot.
> 
> @urajeya I updated the code. Please let me know if worked for you

the update worked smoothly i even got booked but then a cancellation message came soon after that. But atleast the script works alright. But since 1 am there is a problem with the OTPs , i am not recieving OTP after the token expires. The initial otp step works fine more often than not, but from the very first token renewal the code fails.

**Comment by pallupz** [comment] 2021-05-06 21:33
> @pallupz As people have reported that this code works, would you mind linking this up in your readme, so that more people could discover and benefit?

Will do

**Comment by devansh7777** [comment] 2021-05-06 21:55
> > > > > Hi All,
> > > > > I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> > > > > Let me know how it works out.
> > > > 
> > > > 
> > > > does it scan for slots from the present day ?
> > > 
> > > 
> > > @bombardier-gif kindly add the feature so that it can scan from the present day like @pallupz did. It is impossible here in bagalore to get a slot.
> > 
> > 
> > @urajeya I updated the code. Please let me know if worked for you
> 
> the update worked smoothly i even got booked but then a cancellation message came soon after that. But atleast the script works alright. But since 1 am there is a problem with the OTPs , i am not recieving OTP after the token expires. The initial otp step works fine more often than not, but from the very first token renewal the code fails.

adding a feature to resend otp after 180 sec might solve the issue tho @bombardier-gif

**Comment by bombardier-gif** [comment] 2021-05-07 04:43
> > > > > Hi All,
> > > > > I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> > > > > Let me know how it works out.
> > > > 
> > > > 
> > > > does it scan for slots from the present day ?
> > > 
> > > 
> > > @bombardier-gif kindly add the feature so that it can scan from the present day like @pallupz did. It is impossible here in bagalore to get a slot.
> > 
> > 
> > @urajeya I updated the code. Please let me know if worked for you
> 
> the update worked smoothly i even got booked but then a cancellation message came soon after that. But atleast the script works alright. But since 1 am there is a problem with the OTPs , i am not recieving OTP after the token expires. The initial otp step works fine more often than not, but from the very first token renewal the code fails.

Hi Devansh,
If possible could you share your mobile number on this email: bombardier-jpg@protonmail.com
Then i can debug and help you. (the thing is me and all my friends got a slot so I dont have a number who wants to book a slot )

**Comment by bombardier-gif** [comment] 2021-05-07 04:44
> > > > > > Hi All,
> > > > > > I just updated the logic to make it much simpler. I removed the extendsclass and replaced with something more reliable. And also now you dont need to update the change the code.
> > > > > > Let me know how it works out.
> > > > > 
> > > > > 
> > > > > does it scan for slots from the present day ?
> > > > 
> > > > 
> > > > @bombardier-gif kindly add the feature so that it can scan from the present day like @pallupz did. It is impossible here in bagalore to get a slot.
> > > 
> > > 
> > > @urajeya I updated the code. Please let me know if worked for you
> > 
> > 
> > the update worked smoothly i even got booked but then a cancellation message came soon after that. But atleast the script works alright. But since 1 am there is a problem with the OTPs , i am not recieving OTP after the token expires. The initial otp step works fine more often than not, but from the very first token renewal the code fails.
> 
> adding a feature to resend otp after 180 sec might solve the issue tho @bombardier-gif

Aah let me try. Also could you  please create an issue in my repo? There are multiple threads in this issue and i dont want to miss important inputs
