### ISSUE TITLE
403 ERROR

### ISSUE THREAD

**Issue by ab-jiteshlalwani** [pallupz/covid-vaccine-booking#45] opened 2021-05-05 15:24 UTC
Got 403 ERROR. Does it seem that this has been blocked forever?

P.S. It was working fine and I was able to book an appointment 1 hour ago.

**Comment by sixfooter** [comment] 2021-05-05 15:34
yes, this has stopped working. getting this issue- 
++++++++++++++++++++++
Unable to Create OTP
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: UMQFkijztlNRnHr0ohMJ9wGSXzgwl7op1FvOzIyd5N3JcOM8VoLQjQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
Press any key to continue . . .

**Comment by pallupz** [comment] 2021-05-05 15:35
Oh well.. I guess the party is over

**Comment by sixfooter** [comment] 2021-05-05 15:39
would it stilll work via the unix route?

**Comment by pallupz** [comment] 2021-05-05 15:41
Probably not. It might be related to secret key in the generate OTP endpoint. So far I could get away with a hardcoded value. 

https://github.com/pallupz/covid-vaccine-booking/blob/65470fc132c3cbd2099b1a38ced3f654c65d6cb4/src/utils.py#L413

**Comment by sixfooter** [comment] 2021-05-05 15:41
anyway to bypass this by using the OTP generated from mobile phone/ cowin website ? i know that the same passwd remains valid for an extended period of time..

**Comment by sixfooter** [comment] 2021-05-05 15:42
so if we login thru the cowin website and generate the password but use it from yr platform.. ?

**Comment by pallupz** [comment] 2021-05-05 15:43
Nope that's not working either

**Comment by pallupz** [comment] 2021-05-05 15:44
So this is probably not related to the key

**Comment by sixfooter** [comment] 2021-05-05 16:02
Hmm. have they changed the APIs and hence would require an equivalent change in yr code as well. 
I tried to generate an OTP from the Cowin s own website directly and was able to do so.

https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2#/User%20Authentication%20APIs/generateOTP

**Comment by kashishgrover** [comment] 2021-05-05 16:07
@sixfooter that api doesn't work. Check on the cowin website the api they use is the same as the one in the script

**Comment by kashishgrover** [comment] 2021-05-05 16:08
It might be worth extracting out just the `check_calendar` functionality since that api doesn't need otp verification. @pallupz what do you think?

**Comment by pallupz** [comment] 2021-05-05 16:13
@kashishgrover Sure but there are plenty of web-based solutions for those. 

The main idea here was that people can get notified _and_ book an appointment from a single window. In calendar monitoring, by the time we get a notification, then attempt to login to the portal, wait for OTP, select the beneficiary and everything else, slots would be filled.

**Comment by pallupz** [comment] 2021-05-05 16:14
@sixfooter I dont think that's the issue here.

**Comment by pallupz** [comment] 2021-05-05 16:14
If anyone figures this out, please do let me know

**Comment by vinayd2** [comment] 2021-05-05 16:15
Not sure if the rate limiter banner described on the banner is new https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2 

A discussion has started here https://github.com/cowinapi/developer.cowin/issues/19

**Comment by kashishgrover** [comment] 2021-05-05 16:15
> @kashishgrover Sure but there are plenty of web-based solutions for those.
> 
> The main idea here was that people can get notified _and_ book an appointment from a single window. In calendar monitoring, by the time we get a notification, then attempt to login to the portal, wait for OTP, select the beneficiary and everything else, slots would be filled.

Agreed, IMO this was too good to be true anyway...

**Comment by pallupz** [comment] 2021-05-05 16:18
About this: https://github.com/cowinapi/developer.cowin/issues/19#issuecomment-832821755

I tried adding the header info too. Dint work for me.

**Comment by ArjunNair** [comment] 2021-05-05 16:18
Looks like their API endpoints have changed to:
/v2/auth/generateOTP

and 
/v2/auth/confirmOTP

respectively now. Although plugging the same in my Rust implementation (WIP) didn't help...

**Comment by pallupz** [comment] 2021-05-05 16:22
Yea. I'm building it again now.

**Comment by sixfooter** [comment] 2021-05-05 16:23
Does this work on macOS? 
https://github.com/cowinapi/developer.cowin/issues/19#issuecomment-832825274

**Comment by pallupz** [comment] 2021-05-05 16:35
And we are back!

**Comment by franklingeofrancis** [comment] 2021-05-05 16:39
@pallupz  - the pincode flow is working but the state/district option isn't - possibly a minor bug, can you please have a look.

**Comment by pallupz** [comment] 2021-05-05 16:42
That is weird. They both use the same header.

**Comment by pallupz** [comment] 2021-05-05 16:43
Found the bug. Will patch soon

**Comment by bhattparth89** [comment] 2021-05-05 16:45
is there any update over this ?

**Comment by mvmilanjain** [comment] 2021-05-05 16:45
@pallupz  what was the issue?

**Comment by pallupz** [comment] 2021-05-05 16:46
To get the state and districts, earlier we dint need to pass a header. Now we have to.

**Comment by pallupz** [comment] 2021-05-05 16:48
It should be working now @franklingeofrancis

**Comment by pallupz** [comment] 2021-05-05 16:51
@vinayd2 many thanks for the discussion link

**Comment by vinayd2** [comment] 2021-05-05 16:52
wonderful work @pallupz .!

**Comment by bitshiftr** [comment] 2021-05-05 16:55
script stops working after the session ends and it requires a new otp with the following error:

Token is INVALID.
Try for a new Token? (y/n): y
Try for OTP with mobile number XXXXXXXXXX? (y/n) : y
generate_token_OTP() missing 1 required positional argument: 'request_header'
Exiting Script

**Comment by pallupz** [comment] 2021-05-05 16:56
oh

**Comment by mvmilanjain** [comment] 2021-05-05 16:56
exe file still not working

**Comment by mvmilanjain** [comment] 2021-05-05 16:58
Can you expose it as Open APIs so that we can create UI Interface. And great work @pallupz

**Comment by pallupz** [comment] 2021-05-05 17:00
@bitshiftr the issue has been fixed

**Comment by pallupz** [comment] 2021-05-05 17:01
@mvmilanjain what error are you getting? I dont have the faintest idea on how to "expose it as Open APIs"

**Comment by mvmilanjain** [comment] 2021-05-05 17:07
![image](https://user-images.githubusercontent.com/26054025/117181004-69951180-adf2-11eb-92a5-b18e5b9c41ea.png)

**Comment by mvmilanjain** [comment] 2021-05-05 17:07
@pallupz Please check above image

**Comment by mvmilanjain** [comment] 2021-05-05 17:10
@pallupz I facing this issue while generating OTP. In first call only.

**Comment by pallupz** [comment] 2021-05-05 17:12
@mvmilanjain Looks like duplicate of #17

**Comment by bitshiftr** [comment] 2021-05-05 17:23
I downloaded the modified script and ran it, but it failed again after the 1st session with the same error...

**Comment by pallupz** [comment] 2021-05-05 17:25
at which stage?

**Comment by pallupz** [comment] 2021-05-05 17:29
@bitshiftr Could  you try now?

**Comment by pallupz** [comment] 2021-05-05 17:30
with the latest version

**Comment by bitshiftr** [comment] 2021-05-05 17:31
will try and report back

**Comment by mvmilanjain** [comment] 2021-05-05 17:34
@pallupz How can i use generateMobileOtp api from postman?

**Comment by pallupz** [comment] 2021-05-05 17:40
@mvmilanjain you can see the details in this function: https://github.com/pallupz/covid-vaccine-booking/blob/774b6bf6aa21b8f694bbfbfdc9a2d0a255b86d6a/src/utils.py#L413

PS: Code quality is shit

**Comment by bitshiftr** [comment] 2021-05-05 17:49
still facing the same issue:

generate_token_OTP() missing 1 required positional argument: 'request_header'
Exiting Script

**Comment by pallupz** [comment] 2021-05-05 17:51
Are you running exe or python?

**Comment by pallupz** [comment] 2021-05-05 17:52
Try python, it is working for me. EXE should work too. Will check tomorrow

**Comment by bitshiftr** [comment] 2021-05-05 17:52
python - downloading zip every time you asked me to test

**Comment by pallupz** [comment] 2021-05-05 17:53
![image](https://user-images.githubusercontent.com/63504047/117186857-e4f9c180-adf8-11eb-8411-ccd408486bdf.png)
It did work here. See the timestamp

**Comment by bitshiftr** [comment] 2021-05-05 17:55
strange.. I am on a mac, but that shouldn't make a difference.. sorry about the dumb question, but you committed the change and pushed it, right?

**Comment by pallupz** [comment] 2021-05-05 17:55
I did. The exe creation is set on GitHub Actions. So I always push.

**Comment by bitshiftr** [comment] 2021-05-05 17:57
so strange.. I downloaded the latest zip and ran it.. will try tomorrow morning again.. btw, thanks much for doing this - really appreciate your gesture during the crazy time we are going through

**Comment by pallupz** [comment] 2021-05-05 17:58
Also, if you look at the code, ```generate_token_OTP``` function is always called with two params.

**Closed by pallupz** 2021-05-05 17:58 UTC

**Comment by bitshiftr** [comment] 2021-05-05 18:02
this is super strange - in the file I downloaded, the code says:

tryOTP = input('Try for a new Token? (y/n): ')
                if tryOTP.lower() == 'y':
                    if mobile:
                        tryOTP = input(f"Try for OTP with mobile number {mobile}? (y/n) : ")
                        if tryOTP.lower() == 'y':
                            token = generate_token_OTP(mobile)
                            token_valid = True
                        else:
                            token_valid = False
                            print("Exiting")
                    else:
                        mobile = input(f"Enter 10 digit mobile number for new OTP generation? : ")
                        token = generate_token_OTP(mobile)
                        token_valid = True

as you can see it's missing the 2nd param

**Comment by bitshiftr** [comment] 2021-05-06 06:22
just realized what's going on - the main branch is updated but the auto book branch is still 14 hours behind. Can you please merge the changes - thanks!

**Comment by pallupz** [comment] 2021-05-06 06:38
yea, my bad - just use the main branch

**Comment by bitshiftr** [comment] 2021-05-06 06:44
no worries, thanks for confirming.. last request - if you can add the ability to choose vaccine type, that would resolve my biggest requirement :)
