### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by kiranss1** [pallupz/covid-vaccine-booking#28] opened 2021-05-05 06:36 UTC
I am getting this below error after enterring the registered phone number.

> Enter the registered mobile number: ******
> Requesting OTP with mobile number ******..
> HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/auth/generateMobileOTP (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
> Exiting Script
> Press any key to continue . . .

**Comment by pallupz** [comment] 2021-05-05 08:01
Seems like a duplicate of: https://github.com/pallupz/covid-vaccine-booking/issues/17

**Closed by pallupz** 2021-05-05 08:01 UTC
Labels: duplicate
